--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.5
-- Dumped by pg_dump version 9.6.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;


create table if not exists movie
(
    id bigint generated by default as identity
    constraint usr_pkey
    primary key,
    name text not null unique,
    description text,
    typ text
);

create table if not exists sysusr
(
    id bigint generated by default as identity
    constraint usr_pkey
    primary key,
    name text not null unique,
    description text,
    typ text
);

create table sysusr
(
    id            bigint generated by default as identity
        primary key,
    code          dmn_code
        unique,
    upass         text,
    is_active     boolean default true not null,
    full_name     text,
    email         text
        unique,
    zlins_dttm    timestamp with time zone,
    zlupd_dttm    timestamp with time zone,
);

--
-- PostgreSQL database dump complete
--